### PR TITLE
Reducing disk I/O operations by reusing local var value

### PR DESCRIPTION
**Pull request by greenozon**

### CODE REVIEW

**Comment by mrexodia** [comment]
That makes sense, thanks! Originally this was a fix for https://github.com/x64dbg/x64dbg/issues/1635, but I guess I made a copy-paste error.

**Comment by greenozon** [comment]
Great, thanks!
1 more question: should the lines ## 89 & 90 be moved inside the above subroutine GetPeArch()?
https://github.com/x64dbg/x64dbg/blob/1ec3031aca1b525b43ecb4fc7345bc36fd7b3153/src/dbg/commands/cmd-debug-control.cpp#L89

**Comment by mrexodia** [comment]
I don't think so, that's a check specific to x64dbg to figure out what architecture the AnyCPU binary will run with.

**Comment by mrexodia** [comment]
It seems that this change has caused a regression, see https://stackoverflow.com/a/7914778/1806760

**Comment by greenozon** [comment]
Yeah, might be.. it means that  we may still get back to refactoring idea to keep all the arch related operations inside just 1 API
and not outside of it like..  - 
if(arch == PeArch::DotnetAnyCpu)

Otherwise if someone else would like to call GetPeArch()  they have to add afterwards if()... logic?..

**Pull request merged**
