### PR TITLE
Add Icon to right click Context menu for shell extension.

### PR DESCRIPTION
**Pull request by blaquee**
In reference to comment in issue #538

[Review on Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/552)

### CODE REVIEW

**Comment by mrexodia** [comment]
You should run install.bat and let astylewhore format your tabs away on commit :)

**Comment by blaquee** [comment]
weird, it usually does fix it for me when I commit.

**Comment by mrexodia** [comment]
Yea sometimes the formatter fucks up somehow... It's an easy fix anyway.

Visual studio should rip xamarin studio with per-solution formatting and
tab options

**Comment by blaquee** [comment]
Yea it seems like it would be an easy addition using their property sheets. so what should I do? recommit or something?

**Comment by mrexodia** [comment]
Property sheets? How do you mean?

**Comment by mrexodia** [comment]
Oh nevermind :) nah, just format the code to use four spaces and I will
merge it.

**Comment by vgturtle127** [comment]
:+1:

**Pull request merged**
