### PR TITLE
Return RUNTIMEFUNCTION from DbgFunctionGet for better GUI

### PR DESCRIPTION
**Pull request by torusrxxx**
Now almost every function is clearly bounded in the disassembly view.

### CODE REVIEW

**Comment by mrexodia** [comment]
I don't really want to merge this change without a setting because it's confusing and gives a false impression that analysis has been done. In addition there is no guarantee this data is valid at all and even in valid executables the ranges can be split up.

**Comment by torusrxxx** [comment]
So what about a new analysis called "runtimefunctionanalysis" that simply copies RUNTIMEFUNCTION to x64dbg functions?

**Comment by mrexodia** [comment]
I’m pretty sure this command already exists :)

**Comment by torusrxxx** [comment]
So let's add `exanalyse` to the analysis menu? Definitely better than other analyse.

**Comment by mrexodia** [comment]
I think in some ways it's worse. But if `exanalyse` is extended to merge multiple `RUNTIME_FUNCTION` entries that are part of the same function I think it's a really good idea!

**Comment by mrexodia** [comment]
I added a follow-up issue, but I will close this one.

**Pull request closed without merging**
