### PR TITLE
Use https for links

### PR DESCRIPTION
**Pull request by imba-tjd**
Trivial

### CODE REVIEW

**Comment by mrexodia** [comment]
Not all these links work with HTTPS, so not trivial 😄

**Comment by imba-tjd** [comment]
Yeah. `https://blog.x64dbg.com/` and `https://plugins.x64dbg.com/` doesn't work, even though `http://blog.x64dbg.com/` redirs to `https://x64dbg.com/blog/`

**Comment by mrexodia** [comment]
This is because I’m using the redirect.name service. I have to switch this to some dedicated infrastructure, but as you can imagine this is not my favorite task 😄

**Comment by imba-tjd** [comment]
I changed `https://[^.]+?\.x64dbg\.com` to http

**Comment by mrexodia** [comment]
Thanks!

**Pull request merged**
