### PR TITLE
Keystone: for short jumps, reject commands larger than 2 bytes

### PR DESCRIPTION
**Pull request by RaMMicHaeL**
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/1134)

### CODE REVIEW

**Comment by RaMMicHaeL** [comment]
For asmjit, I've created an issue: https://github.com/asmjit/asmtk/issues/4

**Comment by mrexodia** [comment]
Thanks a lot!

**Comment by mrexodia** [comment]
I can also just copy your patch to
https://github.com/x64dbg/asmjit_xedparse/blob/master/asmjit/XEDParseEmulator.cpp

**Comment by RaMMicHaeL** [comment]
You can do this as a temporary solution, until https://github.com/asmjit/asmjit/issues/138 is properly solved.
Frankly, I don't know what are the advantages of asmjit over Keystone, or vice versa. They both seem like high quality projects, and Keystone seems to work pretty well with Multiline Ultimate Assembler.
For XEDParse, there are still commands which it doesn't support. For example, a command which I found in a short testing session: `mov edx, dword ptr [0x7ffe0330]`

**Comment by mrexodia** [comment]
@RaMMicHaeL what exactly is the problem with `mov edx, dword ptr [0x7ffe0330]` it outputs to `8B 15 30 03 FE 7F` to me which appears to be fine... I will add the workaround for short jumps in asmjit. Keystone and asmjit are just both supported. Currently the advantage of asmjit is that it supports symbols but keystone is adding support too. Another advantage of asmjit is that it's smaller but that's hardly relevant for x64dbg 😄

**Comment by RaMMicHaeL** [comment]
Here's what I see...

**Comment by mrexodia** [comment]
Oh yeah I tried on 32 bits.

**Comment by RaMMicHaeL** [comment]
It's fairly easy to find these kinds of issues: disassemble a large block with Multiline Ultimate Assembler, and then assemble it back. Here's another one: `and rax, 0xfffffffffffff000`

**Comment by mrexodia** [comment]
Yeah they are easy to find maybe @Nukem9 should check them.

**Comment by mrexodia** [comment]
@RaMMicHaeL I have updated asmjit to error on short jumps it should be deployed some time soon.

**Comment by RaMMicHaeL** [comment]
It works perfectly, thanks!

**Comment by RaMMicHaeL** [comment]
It works perfectly, thanks!

One additional thing that I'm not sure whether it should be fixed in the debugger or in the plugin:
Some commands, especially which use addressing, disassemble differently in the plugin. For example:
pic

The plugin uses the `DisasmFast` function. Is that what it should be using?

**Comment by mrexodia** [comment]
Yeah the rip-relative thing is just a hack, see
https://github.com/x64dbg/x64dbg/blob/development/src/gui/Src/Gui/CPUDisassembly.cpp#L939

**Comment by RaMMicHaeL** [comment]
I guess that it would be best to make the hacks and the customization (such as uppercase disasm) available to plugins, too.

**Comment by mrexodia** [comment]
They are you can use GuiDisasmGet if you want the exact representation the
GUI has with labels and uppercase 👍🏻

**Comment by RaMMicHaeL** [comment]
I didn't find that one.
https://github.com/x64dbg/x64dbg/search?utf8=%E2%9C%93&q=GuiDisasmGet&type=Code

**Comment by mrexodia** [comment]
I meant GuiGetDisassembly but I wouldn't recommend using it because it
includes module names and labels and such.

**Comment by RaMMicHaeL** [comment]
OK, so my suggestion still applies. I think that plugins should be able to get the same disasm that the user gets when pressing space (which is with the hack, and with case customization, but without labels and such). If that's not going to happen, I might copy the hack to the plugin one day, but this solution is not very elegant.

**Comment by mrexodia** [comment]
Yeah I agree that it would be the best thing. Please open a new issue
though I will see if I can implement it.

**Comment by RaMMicHaeL** [comment]
> You can do this as a temporary solution, until asmjit/asmjit#138 is properly solved.

The issue was fixed in asmjit, so you can revert the hack once you update the asmjit version.

**Comment by mrexodia** [comment]
Alright cool!

**Pull request merged**
