### PR TITLE
Misc. GUI improvement

### PR DESCRIPTION
**Pull request by torusrxxx**
1. Address the following issue:
      #612 : save log
      #613 : copy all registers
      #373 : disable log
2. Add a menu item to hide debugger.
3. Updated translation

---
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/646)

### CODE REVIEW

**Comment by mrexodia** [comment]
Looking great, the only part I think can be done more efficient is [copyAllRegisters](https://github.com/x64dbg/x64dbg/pull/646/files#diff-5001e759717db851606a425869b3ff1aR2029) it looks like a gigantic code duplicate to me. Is it possible to generate calls to a function like `appendRegister(QString & text, REGISTER_NAME reg, const char* name32, const char* name64)` instead?

**Comment by torusrxxx** [comment]
all done

**Comment by mrexodia** [comment]
Reviewed 11 of 12 files at r1, 1 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/gui/Src/Gui/RegistersView.cpp, line 0 \[r1\]](https://reviewable.io:443/reviews/x64dbg/x64dbg/646#-KIGeDvxM6TRZHz4bbIM:-KIGeDvy2d14NMY4vUI9:160371488) ([raw file](https://github.com/x64dbg/x64dbg/blob/5ffe5b14a9fd1f78f2efd7ab7fd0bc7b56fde7ce/src/gui/Src/Gui/RegistersView.cpp#L0)):*
BTW

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/x64dbg/x64dbg/646)*

**Comment by torusrxxx** [comment]
appendRegister() produces compiler warning......

**Comment by mrexodia** [comment]
I fixed the compiler warning.

**Pull request merged**
