### PR TITLE
Make register view larger in x64 mode

### LINKED ISSUE #701: Register view is too small to display YMM8~YMM15
x64dbg-register-window-too-small

### PR DESCRIPTION
**Pull request by torusrxxx**
Fix #701

---
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/703)

### CODE REVIEW

**Comment by mrexodia** [comment]
What does this look like if you compare it with the current view?

**Comment by torusrxxx** [comment]
The only difference is that the register view can scroll down more, revealing the content behind. And some space behind DRX.

**Comment by torusrxxx** [comment]
x64dbg-register-view-extended

**Comment by mrexodia** [comment]
it looks like this for me without this will is not show all the data on your side?

img

**Comment by torusrxxx** [comment]
Different systems have different default font sizes.

**Comment by mrexodia** [comment]
So I guess a proper fix would be to have this size be something like `fontHeight * x`?

**Comment by mrexodia** [comment]
resolved in c4234d3

**Pull request closed without merging**
