### PR TITLE
Create .gitattributes

### PR DESCRIPTION
**Pull request by Huemac**
You seem to have issues with inconsistent line endings. 

Please read more about .gitattributes here: https://help.github.com/articles/dealing-with-line-endings/

The above file is a simple example.

---
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/733)

### CODE REVIEW

**Comment by mrexodia** [comment]
We solve this problem by auto formatting with a custom tool.

**Comment by Huemac** [comment]
Does your custom tool trigger if you make a change directly from Github web application? 

Sometimes useful when raising e.g. a version number in some header etc...

**Comment by mrexodia** [comment]
Nope, the tool runs with a pre-commit hook. Thanks though, I will look into it.

**Comment by mrexodia** [comment]
Thanks!

**Pull request merged**
