### PR TITLE
Window title obfuscation

### PR DESCRIPTION
**Pull request by torusrxxx**
All the softwares search "OllyDbg" window in the system. Will x64dbg enjoy comparable fame?
x64dbg-window-title-obfuscation

---
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/759)

### CODE REVIEW

**Comment by mrexodia** [comment]
I believe there are also window classes that are detectable. Can you check this with some handle viewer?

Generally the window is already obfuscated though because of the changing title.

**Comment by torusrxxx** [comment]
I think setting window title to the executable name is better because the user can then rename the executable, enabling custom-style obfuscation.
Using a handle viewer with this feature on I found the following windows:
[Title: (Main window)] [Class name: `Qt5QWindowIcon`]
> [Title: `MHTabWidgetClasWindow`] [Class name: `Qt5QWindowIcon`]
> [Title: (null)] [Class name: `Qt5QWindowIcon`]
> [Title: `statusBarWindow`] [Class name: `Qt5QWindowIcon`]
> [Title: (null)] [Class name: Qt5QWindowIcon]
> [Title: `menuBarWindow`] [Class name: `Qt5QWindowIcon`]

[Title: (executable name)] [Class name: `Qt5QWindowIcon`]
[Title: (executable name)] [Class name: `Qt5QWindowPopupDropShadowSaveBits`]
[Title: (executable name)] [Class name: `Qt5QWindowPopupDropShadowSaveBits`]

So you can see without this feature `FindWindow` will be able to find a window named `x64dbg`

**Comment by mrexodia** [comment]
Alright, sounds great then! I will check the code and then merge the pull
request.

**Comment by mrexodia** [comment]
We could also just put an option in the ini file.

**Comment by mrexodia** [comment]
Thanks!

**Pull request merged**
