### PR TITLE
HardcoreThreadSwitchWarning

### PR DESCRIPTION
**Pull request by torusrxxx**
It has been a hidden setting for a long time.

---
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/1274)

### CODE REVIEW

**Comment by torusrxxx** [comment]
Oh I don't want to update "capstone_wrapper"

**Comment by mrexodia** [comment]
Why?

**Comment by torusrxxx** [comment]
github says I have committed something to "capstone_wrapper" in this pull request, but it is a mistake if I really do.

**Comment by mrexodia** [comment]
You don't have the latest version of capstone_wrapper in your submodules.

**Comment by torusrxxx** [comment]
Yes I don't want to update it now because there are some modifications to it to make the tracer working.

**Pull request merged**
