### PR TITLE
Added mnemonic brief column and keeps mnemonic brief configuration

### PR DESCRIPTION
**Pull request by torusrxxx**
The hidden by default mnemonic brief column helps keep comments column clean while showing mnemonic brief. It also remembers mnemonic brief settings.

### CODE REVIEW

**Comment by mrexodia** [comment]
I don’t like this idea. This column is something I toggle quickly if I forget the instruction, it’s not something to keep enabled and adding it next to the comments makes it invisible unless you mess around too much…

**Comment by mrexodia** [comment]
And I think I misunderstood, it looks like you can manually move the mnemonic brief to the column if you unhide it.

**Comment by torusrxxx** [comment]
Newbies need to permanently enable mnemonic brief until they get used to it. The mnemonic brief is moved to the new column, so that the comments column stay clean and you can also make mnemonic brief column narrow to see only a few words, compared to always show mnemonic brief in full currently. There's no change to the default GUI.

**Comment by mrexodia** [comment]
Will do some merging when I'm back home tomorrow!

**Comment by mrexodia** [comment]
👍🏻

**Pull request merged**
