### PR TITLE
DBG: Fixed DLL breakpoints.

### PR DESCRIPTION
**Pull request by jackreez**
DLL breakpoints can now be enabled/disabled/removed!

### CODE REVIEW

**Comment by mrexodia** [comment]
Thanks! @Mattiwatti says it’s working

**Comment by jackreez** [comment]
> Thanks! @Mattiwatti says it’s working

@Mattiwatti 
Is it? What's wrong with this? Kindly, let me know!

**Comment by mrexodia** [comment]
Nono, there is nothing wrong. Matti said it was working good 🙂

**Comment by jackreez** [comment]
> > Thanks! @Mattiwatti says it’s working
> 
> @Mattiwatti
> Is it? What's wrong with this? Kindly, let me know!

Sorry, for misunderstanding! My machine's screen is glitchy 😢!

**Comment by mrexodia** [comment]
Everything is correct, nothing to worry about!

**Pull request merged**
