### PR TITLE
Tab switch using history stack

### PR DESCRIPTION
**Pull request by lynnux**
Implement [#1805](https://github.com/x64dbg/x64dbg/issues/1805), 
Press <Alt+Right>/<Alt+Left> to give a try. It's maybe a little strange in <Alt+Left>, usually <Alt+Right> is enough, it quickly switch to the previous view.

use the popup code from the qt creator source, like this:

also, detached window was well handled.

### CODE REVIEW

**Comment by lynnux** [comment]
wait... maybe I should assign shortcut <Alt+Left>and<Alt+Right> to this, so user can cutomize the shortcuts.

**Comment by lynnux** [comment]
In recent commit, I  rename HistoryViewsPopupWindow to MultiItemsSelectWindow, the idea is that:
I wish there would have some shortcuts for "Follow in Dump/Disassembler/Stack/MemoryMap", but usaully it will have more than one choice to select:

So it's can't to select one without mouse. My idea is binding a shortcut like <CTRL+1> to "Follow in Dump", when press <CTRL+1>, it popup a window like:

to choose one entry you don't need mouse, only continue to press <CTRL+1> it will goto next entry, and you can bind <CTRL+SHIFT+1> to go back. same idea can apply to other "Follow in ..."

**Comment by mrexodia** [comment]
Hm, one of my messages got lost in Github's email (@support)

You shouldn’t do any shortcuts with Alt... I think if we change the behaviour it should replace Ctrl+Tab

**Comment by mrexodia** [comment]
Also that idea for the dump sounds useful! I was thinking of changing the double click so a menu pops up with various options where to follow it...

**Comment by lynnux** [comment]
Don't know which way people like, my init implement is to replace CTRL+TAB, but they can coexist now.  In private, I will bind CTRL+TAB to this.
Double click may encounter a problem that which target it will follow, my idea is that CTRL+1 to follow in disassembler, CTRL+2 to  follow in dump, CTRL+3 to follow in stack, no matter where you locate at.  Of course you can place all options in one menu, but it's may not straight forward, need people to think about which entry he/she should choose.

**Comment by mrexodia** [comment]
Thanks! I swapped the hotkey for this with previous/next tab because it makes more sense, I also made some small style changes but it works fine!

**Comment by torusrxxx** [comment]
x64dbg_translations.pro

**Comment by mrexodia** [comment]
Hm I have to remove that file some day, the translator has support for files from multiple sources...

But I will update it

**Pull request merged**
