### PR TITLE
Add CTRL+1/CTRL+2, which popup a window to follow in disam/dump

### PR DESCRIPTION
**Pull request by lynnux**
if there are more than one choice, just continue CTRL+1/CTRL+2 to loop selection.

### CODE REVIEW

**Comment by lynnux** [comment]
The source of data is the same as the right menu, but seems have bug like showed in the gif.

**Comment by torusrxxx** [comment]
不美观

**Comment by lynnux** [comment]
实用是硬道理啊，一直都没有StrongOD那样的快捷键，查看数据一直都是鼠标右键菜单很不方便的

**Comment by torusrxxx** [comment]
挡住后面了，没有办法移动，而且新用户不知道可以用这个，窗口显示出来了也不知道能干什么。

**Comment by lynnux** [comment]
这个跟新版CTRL+TAB切换是一样的，一松手窗口就没有了，然后就定位到第一个选中项了，如果要选择第二个就不要松CTRL，继续按1/2。
菜单可以加一个，但因为没有按CTRL只能定位到第一个项。
你可以checkout这个branch试试效果。

**Comment by torusrxxx** [comment]
那你可以在窗口下面写两句话告诉新用户这个窗口可以干嘛吧，或者显示一下可以用Ctrl+1、Ctrl+2继续移动，然后在最后加个取消选项，不过不加也可以，可以跳转后再用鼠标后退键回来。

**Comment by lynnux** [comment]
Yes, I will try improve tip when I'm free

**Comment by lynnux** [comment]
The new unified tip is "Follow %1 in %2":


And I wonder if there need a new shortcut entry in menu, maybe we can add tip in current right menu like this:

**Comment by mrexodia** [comment]
I think if you append “\tCtrl+1” it will put it on the right...

**Comment by lynnux** [comment]
Thanks for the tip! I append the shortcut hint in current menu:

**Comment by mrexodia** [comment]
@torusrxxx do you think the functionality has improved enough to merge it?

**Comment by torusrxxx** [comment]
`tr("Follow in Dump\t%1").arg(ConfigShortcut("ActionFollowDumpPopup").toString()`
=>
`tr("Follow in Dump").append('\t').append(ConfigShortcut("ActionFollowDumpPopup").toString()`

**Comment by mrexodia** [comment]
Sorry for the delay, I would like to test this better before I merge it but I didn't have much time recently... I will ask in the channel if people can test this.

**Comment by mrfearless** [comment]
tried out the release, here is the issues or things I observed:

* <kbd>CTRL</kbd>+<kbd>1</kbd> / <kbd>CTRL</kbd>+<kbd>2</kbd> brings up popup window, if I release <kbd>CTRL</kbd> button it auto selects first selection.
* <kbd>CTRL</kbd>+<kbd>ESC</kbd> (keeping <kbd>CTRL</kbd> held down) does escape popup window but also brings up windows menu - so maybe losing focus is really the reason it closes without doing a selection.
* <kbd>CTRL</kbd>+<kbd>2</kbd> on a line bring up popup window. Escape popup window without making selection. Select a new dump tab. <kbd>CTRL</kbd>+<kbd>2</kbd> now shows popup window that is blank.
* Mousewheel doesnt move selection bar up/down.

**Comment by lynnux** [comment]
@mrfearless, thanks for the test. 

- yes, it's worked like ctrl+tab
- there is no cancel operation now, I've tried implemented like this on my local repo:
, and ctrl+esc is captured by system which may can not be captured by x64dbg.
-  ...
- It's a good idea to add ctrl+wheel up/down! However, I've tried ctrl+wheel which only work if mouse cursor are on the popup window.

**Comment by mrexodia** [comment]
@lynnux why did you close it?

**Comment by lynnux** [comment]
It's passed almost 6 months since first pull request,  I think this will not be merged, so I closed and just use for personal.

**Pull request closed without merging**
