### PR TITLE
Fix crash in function 'ProcessFileSections'

### PR DESCRIPTION
**Pull request by gmh5225**
Fix a crash caused by some virus modifications to the pe header.

### CODE REVIEW

**Comment by mrexodia** [comment]
Could you share the executable on malshare?

**Comment by gmh5225** [comment]
Sorry. I can't provide this sample right now due to some limitations. The main behaviour of this example is to make modInfo->headers=0 and modify the pe header.

**Comment by mrexodia** [comment]
Can you send me just the header bytes or a summary of the PE (sections, optional header) with stuff redacted? I need to be able to reproduce this behavior locally and add it to my testbed…

**Comment by mrexodia** [comment]
Actually I noticed you modified an old version that had a bug where the module name was used instead of the address to find the module. Could you try the latest version and see if it’s still bugged?

**Comment by gmh5225** [comment]
> Actually I noticed you modified an old version that had a bug where the module name was used instead of the address to find the module. Could you try the latest version and see if it’s still bugged?

I'm really, really sorry. I forgot to upstream, no problem with the new version. I think I should close this PR. 0.0

**Comment by mrexodia** [comment]
Would still appreciate some information on that malware. It was clearly triggering something weird…

**Pull request closed without merging**
