### PR TITLE
Fixed Hotlink

### PR DESCRIPTION
**Pull request by ThomasThelen**

### CODE REVIEW

**Comment by mrexodia** [comment]
No the link is not broken. Just try clicking it and you'll see it takes you to the correct page.

**Comment by ThomasThelen** [comment]
Hmm it was broken at the time I committed this.
broken

**Comment by mrexodia** [comment]
Interesting, maybe the github Markdown parser was updated and had a regression. It's cleaner to not uses spaces inside urls though so I'll merge it.

**Comment by mrexodia** [comment]
Thanks!

**Comment by mrexodia** [comment]
Ehm, Github totally fucked up the merge and I have no idea where it went...

**Comment by ThomasThelen** [comment]
It looks like the link is fixed with the proper dashes-I bet this is fine to close.

**Pull request merged**
