### PR TITLE
Translate the launcher and add more shortcuts

### PR DESCRIPTION
**Pull request by torusrxxx**
The translated strings are stored in "Strings.rc" and loaded via `LoadString`. `LoadString` is the only viable way to get translated strings before the GUI is loaded.
The shortcuts added are :

- ActionEditBreakpoint
- ActionToggleLogging
- ActionAllocateMemory
- ActionFreeMemory
- ActionSyncWithExpression
- ActionEntropy
- ActionCopyAllRegisters
- ActionMarkAsUser
- ActionMarkAsSystem
- ActionMarkAsParty
- AnalysisRemoveAnalysisFromModule
- AnalysisRemoveAnalysisFromSelection
- AnalysisTreatSelectionAsByte
- AnalysisTreatSelectionAsASCII
- AnalysisTreatSelectionAsUNICODE
- ActionSetHwBpE
- ActionRemoveHwBp
- DebugTraceIntoConditional
- DebugTraceOverConditional
- DebugEnableTraceRecordBit
- DebugTraceRecordNone

---
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/793)

### CODE REVIEW

**Comment by mrexodia** [comment]
I don't want to merge the translation because it's ugly and slows down development...

**Comment by torusrxxx** [comment]
Launcher doesn't need to be updated very frequently. Last update was months
ago...

**Comment by mrexodia** [comment]
Yes that's true. I still think we should find a reliable framework to translate it to other languages without having to update resource files in the repository. Also there were changes to the bridge which are not necessary as far as I'm aware.

**Comment by torusrxxx** [comment]
As far as I know there is no such framework except LoadString

**Comment by mrexodia** [comment]
Okay so I will merge this :+1:

**Pull request merged**
