### PR TITLE
Overriding getColor

### PR DESCRIPTION
**Pull request by KhushalPShah**
@torusrxxx 
Please let me know if this is proper.
PS: I am a newbie, so please excuse me for my noviceness.
Let me know if there are changes needed.

thanks!

### CODE REVIEW

**Comment by torusrxxx** [comment]
Please read and follow the instructions at https://github.com/x64dbg/x64dbg/wiki/Compiling-the-whole-project

**Comment by KhushalPShah** [comment]
I am facing some issues with the installations.
Will try and get back
Deleting the PR for now.

Thanks!

**Comment by mrexodia** [comment]
I will update the wiki, but you can only get Visual Studio 2013 from an ISO (they killed the online installer) https://my.visualstudio.com/Downloads?q=visual%20studio%202013&wt.mc_id=o~msft~vscom~older-downloads

image

**Comment by mrexodia** [comment]
any updates on this @KhushalPShah ?

**Pull request closed without merging**
