### PR TITLE
Fix Shift key combination bug

### PR DESCRIPTION
**Pull request by yjd**

### CODE REVIEW

**Comment by mrexodia** [comment]
Thanks for your contribution! It would help if you could describe the bug in words so it's easier to understand what this actually fixes.

**Comment by yjd** [comment]
@mrexodia 


I type in the Shift+H key combination and it pops up with an error ignoring the Shift key.
Testing any Shift+xxx combination doesn't work.

**Comment by mrexodia** [comment]
Thanks for the info, I will give it a try and let you know!

**Comment by mrexodia** [comment]
Sorry for the late reply, thanks for the fix!

**Pull request merged**
