### PR TITLE
Fetch mCmdHistory on an empty mCmdLineEdit

### PR DESCRIPTION
**Pull request by lyflow**
Hi 👋, 

I made some change in accordance with issue #2107 
Please, keep in mind that that I am _not_ used to Qt!

### CODE REVIEW

**Comment by torusrxxx** [comment]
I would accept this change without any options, anyway it is better than nothing on ENTER.

**Comment by mrexodia** [comment]
I don't think I agree. When you press enter with an empty textbox I expect nothing to happen, like most other textboxes.

**Comment by torusrxxx** [comment]
Anyway I don't want to see it stalled for possibly another year, I'll add the option and push it forward.

**Comment by mrexodia** [comment]
Thanks, this feature has been integrated with #2429

**Pull request closed without merging**
