### PR TITLE
GUI improvements

### PR DESCRIPTION
**Pull request by torusrxxx**
*  Forward and Backward mouse buttons found in some models of mice.
*  No confirmation when adding functions.
*  Allocate memory from the dump menu.
*  Placeholder tips for learners.
*  disable/cancel log redirect (issue #939)
*  use windows config singe step size (issue #1000)

---
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/1004)

### CODE REVIEW

**Comment by mrexodia** [comment]
Hm are you sure it's a good plan to not make the user confirm on function or argument deletion? For adding it makes sense but the user might accidentally delete a tool-analyzed function...

**Comment by torusrxxx** [comment]
I often delete the auto functions because that's inaccurate. Maybe we can
log the old function start and end when deleting the function, so the user
can restore it from the log.

**Comment by mrexodia** [comment]
Alright I will just merge it.

**Comment by mrexodia** [comment]
Should I wait until later today with merging?

**Comment by torusrxxx** [comment]
I'm debugging now. No work is pending.

**Comment by mrexodia** [comment]
Alright, thanks a lot!

**Pull request merged**
