### PR TITLE
Allow Option for assembling Instruction on Double Click

### PR DESCRIPTION
**Pull request by Yakov5776**

### CODE REVIEW

**Comment by Yakov5776** [comment]
If someone can enlighten me on what went wrong that'll help

**Comment by mrexodia** [comment]
https://ci.appveyor.com/project/mrexodia/x64dbg/builds/38104977

The formatting of `CPUDisassembly.cpp` is not conforming. You can manually run `format.bat` or use `install.bat` to automatically format on commit. This change looks great though, I'll be happy to merge it!

**Comment by Yakov5776** [comment]
Why is settingboolget undeclared? Is there something I need to include that I'm missing?

**Comment by mrexodia** [comment]
I'll take a look 🙂

**Comment by Yakov5776** [comment]
Ok I'll be waiting I guess

**Comment by mrexodia** [comment]
> Ok I'll be waiting I guess

I think this should work. This api isn't available (it's ugly I know). Instead I used `BridgeSettingGetUint`.

**Comment by mrexodia** [comment]
```
        if(settingboolget("Disassembler", "AssembleOnDoubleClick"))
        duint assembleOnDoubleClick = 0;
        BridgeSettingGetUint("Disassembler", "AssembleOnDoubleClick", &assembleOnDoubleClick);
        if(assembleOnDoubleClick)
        {
            assembleSlot();
        }

```

**Comment by Yakov5776** [comment]
Alright

**Comment by Yakov5776** [comment]
I think that should be it?

**Comment by Yakov5776** [comment]
By looking at the code the if statement looks reversed

**Comment by Yakov5776** [comment]
There

**Comment by Yakov5776** [comment]
Why is settingboolget undefined?

**Comment by Yakov5776** [comment]
Is there like no way checking the configuration from the gui?

**Comment by Yakov5776** [comment]
YA!

**Comment by Yakov5776** [comment]
It works!

**Comment by Yakov5776** [comment]
You can merge it, I've tested it and everything works

**Comment by Yakov5776** [comment]
Can you please submit the pull request so I can contribute some more changes

**Comment by mrexodia** [comment]
Thanks for your contribution!

**Pull request merged**
