### PR TITLE
Added registers/infobox to trace view, Merged graph and disassembly view.

### PR DESCRIPTION
**Pull request by torusrxxx**
x64dbg trace view
x64dbg graph view
The lower right widget is hidden currently.

### CODE REVIEW

**Comment by mrexodia** [comment]
Is this ready to be merged? I saw it too late yesterday and the theme selection and disassembly in dump has been merged which might cause some conflicts in `development`. If it's ready I'll rebase it myself and try if that's okay with you.

**Comment by torusrxxx** [comment]
This is mostly complete but some small improvements could be done.  I auto merged recent changes into this so there should be no conflicts. You can merge this any time you like or wait for me to polish it.

**Comment by mrexodia** [comment]
I tried it, but the graph became kind of small for my taste. When I use it I have the graph full screen normally and now you can no longer detach it. I generally don't use the graph though and this definitely is a way to allow you to debug from there so I'll merge it!

**Comment by mrexodia** [comment]
I pushed some minor improvements, will merge once the CI completes!

**Comment by mrexodia** [comment]
Thanks!

**Comment by justanotheranonymoususer** [comment]
> Merged graph and disassembly

Please, make it to take all space when zoomed out. Otherwise too small and difficult to grasp the full picture. A major regression. Thanks.

**Pull request merged**
