### PR TITLE
show PID or TID in handles view

### PR DESCRIPTION
**Pull request by torusrxxx**
#1961. Tested on Windows XP. It doesn't show process name yet because it is somewhat more expensive.

### CODE REVIEW

**Comment by torusrxxx** [comment]
This assumes the type name "Process" and "Thread" is consistent across Windows versions (seems true). Process names can be retrieved with "GetModuleBaseName" (not done yet). For Windows 10, "GetThreadDescription" might be interesting.

**Comment by mrexodia** [comment]
I tested this on Windows 8.1 and it was working, but on Windows 10 I had some trouble, I will investigate it further...

**Comment by mrexodia** [comment]
Hi, I found a minimal executable that should reproduce the issue I was having:

```
#include <windows.h>

int main()
{
    auto pid = GetCurrentProcessId();
    auto hp = OpenProcess(PROCESS_TERMINATE, FALSE, pid);
    TerminateProcess(hp, 0);
}
```

`GetProcessId` requires `PROCESS_QUERY_INFORMATION`, but duplicating with the same access won't grant it in this case.

**Comment by torusrxxx** [comment]
How do you think to fix this problem? If the debuggee doesn't open a
process with query privileges, its access is very limited, and it is very
likely the debuggee already knows its PID in its memory. I don't want to
fix this bug as almost all process operations require query privilege. A
handle without query privilege can't be useful for viral transmission.

**Comment by mrexodia** [comment]
I think a clean fix would be to re-duplicate the handle with query privileges once we see it’s a process or thread handle. This should be undetectedable and pretty clean (DuplicateHandle has a parameter for access). Maybe today I will try something if I have some time...

**Pull request merged**
