### PR TITLE
Using build number instead of magic number

### PR DESCRIPTION
**Pull request by gmh5225**
Closes https://github.com/x64dbg/x64dbg/issues/2898

### CODE REVIEW

**Comment by mrexodia** [comment]
Thanks! This would need some more significant testing from my side so it might take a while…

For next time feel free to use the phrase “Closes #xxx” in the description and everything will be linked automatically

**Comment by gmh5225** [comment]
"Closes #xxx" is handy. I see. Thank you.

**Comment by gmh5225** [comment]
Tested on both win10(17763 18362) and win11(22000.708)

**Comment by mrexodia** [comment]
Thanks!

**Pull request merged**
