### PR TITLE
Add relative path support to launcher

### PR DESCRIPTION
**Pull request by not6**
#2838

### CODE REVIEW

**Comment by mrexodia** [comment]
The reason there is an absolute path there is because the launcher’s current directory will be next to the program you debug, not next to the launcher itself.

I have to check more thoroughly, but you need to manually resolve the path to be next to the launcher executable instead of getting the full path.

**Comment by not6** [comment]
@mrexodia This version seems to work fine, I don't know why the check fails though.
Also sorry if I do anything dumb, I haven't actually used GitHub or git overall that much before..

**Comment by mrexodia** [comment]
Thanks!

**Comment by MrMendelli** [comment]
I appreciate the efforts made to look into this, thank you.

**Pull request merged**
