### PR TITLE
my first help document

### PR DESCRIPTION
**Pull request by torusrxxx**
WinCHM Pro is not a free software. I'm using a text editor to add documents now. What free alternative can I use?

---
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/757)

### CODE REVIEW

**Comment by mrexodia** [comment]
There is no free alternative as far as I'm aware. I have plans to change
the help to something like readthedocs.org but that has no priority for me
right now, nobody bothers to read the help anyway haha

**Comment by torusrxxx** [comment]
Different potential contributers have different todo lists. Documentation
seems like a very good start point.

**Comment by torusrxxx** [comment]
Maybe you can set up a different repository for the documentation and register it at readdocs.org, then I'll help you migrate the documentation there. Adding a feature without writing documentation for it usually lead to chaos if it doesn't work in the future.

**Comment by mrexodia** [comment]
I invited you to the x64dbg/docs team and you should have access to https://github.com/x64dbg/docs which will be shown at http://help.x64dbg.com

**Comment by torusrxxx** [comment]
Something is wrong with the project configuration. There are zero repositories owned by the team.

**Comment by mrexodia** [comment]
Or sorry about that, will fix it as soon as possible.

**Comment by mrexodia** [comment]
Okay, I added the team, sorry about that. Probably I will find some more
people to convert the documentation over the next week.

**Pull request merged**
