### PR TITLE
GUI: fixed wired process refresh (#697)

### PR DESCRIPTION
**Pull request by yuxuanchiadm**
Fixed wired process refresh #697

---
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/728)

### CODE REVIEW

**Comment by Atvaark** [comment]
I also looked at this a few hours ago and came up with the same solution.

1.
You can also call *refreshSearchList* in the on_checkBoxRegex_toggled function.

2.
I noticed that when a search text is entered and the refresh button is clicked the process list doesn't even refresh.
attach1
attach2


You have to clear the text, hit refresh and reenter the text right now.

**Comment by yuxuanchiadm** [comment]
Yeah. But this is other issue i think. Fixed.

**Comment by yuxuanchiadm** [comment]
And I can reproduce your issue 2. Did I do anything wrong?
* Open x64dbg
* Open Attach window
* Open notepad.exe
* Refresh Attach window
* Close notepad.exe
* Refresh Attach window

Everything looks right. Did you compiled x64gui using qmake with my PR patch?

**Comment by Atvaark** [comment]
You mean you can't reproduce the 2nd issue I mentioned? 

I didn't test it with your changes in AttachDialog::refresh(). Replacing mCurList with mList probably fixes that issue. I can test your changes later but I'm sure it works correctly now.

**Comment by yuxuanchiadm** [comment]
Ok. I probably known what you mean in issue 2. @mrexodia. I think able to megre.

**Comment by mrexodia** [comment]
Thanks!

**Pull request merged**
