### PR TITLE
Toggle "Show Suspected Call Stack Frame" with space

### PR DESCRIPTION
**Pull request by justanotheranonymoususer**
Not sure if gonna work, tried according to this:
https://github.com/x64dbg/x64dbg/blob/58825d4522f06986e09ab17b141204a66e68dd15/src/gui/Src/Utils/ActionHelpers.h#L240

Let's see what the build says.

### CODE REVIEW

**Comment by mrexodia** [comment]
I tested and it's not working. Likely an issue that needs some `keyReleaseEvent` to override the behavior manually.

**Comment by justanotheranonymoususer** [comment]
I don't know how to do that unfortunately. I thought it would be easy. Every time something changes, like loading symbols, I need to refrsh this. The only way now is right clicking and changing view, and then back again. So space could make it simpler. But I failed to implement.

**Comment by mrexodia** [comment]
Hm perhaps it’s better to call the refresh view at the right time? Could
you list all the actions that are not refreshing the table?

**Comment by justanotheranonymoususer** [comment]
Loading symbols is one, most common for me. If thread is paused I think it refreshes. But if it's running and I want to force refresh, there needs to be a way to trigger refresh.

**Comment by mrexodia** [comment]
I think the core problem was fixed. Tracking the hotkey in https://github.com/x64dbg/x64dbg/issues/3034

**Pull request closed without merging**
