### PR TITLE
Tripleslash for scriptapi_misc functions

### PR DESCRIPTION
**Pull request by rotateLeft**

### CODE REVIEW

**Comment by mrexodia** [comment]
The thing is indented with tabs instead of spaces, you can run `format.bat` (or `install.bat` before you commit) to automatically format the sources...

**Comment by rotateLeft** [comment]
Hopefully formatted correctly now. Should I be including a prefix in the git commits? (DBG/GUI etc) ?

**Comment by mrexodia** [comment]
Nah, it's fine perhaps next time you can include the prefix...

**Comment by mrexodia** [comment]
Oh and thanks 👍

**Pull request merged**
