### PR TITLE
Implement Trace over system dlls

### LINKED ISSUE #1884: FeatureRequest - Always trace over system DLL's
Unless I've missed something I can't see an option to trace / animate over System DLL files. There is an option in Ollydbg to do this. 

x64dbg

### PR DESCRIPTION
**Pull request by ZehMatt**
Closes #1884

### CODE REVIEW

**Comment by sityware** [comment]
I've just tried a snapshot from today, and when I animate into / trace into, I'm still getting routed into system dlls e.g ntldll

Even with the condition mod.party(dis.branchdest(cip)) == 1

**Comment by ZehMatt** [comment]
Could you show the lines from the trace where it jumps into a system dll? If your claim is correct that the expression is already not working correctly then its possible that theres another bug hidden.

**Comment by sityware** [comment]
Apologies. I think I have it working now. Many thanks

**Comment by sityware** [comment]
I'm still getting traces into system dlls.

When using:
Animate Into
Trace Into - When using 0x{p:cip} {i:cip} and condition mod.party(dis.branchdest(cip)) == 1

0x00444434 mov eax, dword ptr ds:[eax-0x8]
0x00444437 mov eax, dword ptr ds:[eax+0x4]
0x0044443A push eax
0x0044443B mov eax, dword ptr ss:[ebp+0x8]
0x0044443E mov eax, dword ptr ds:[eax-0x8]
0x00444441 mov eax, dword ptr ds:[eax]
0x00444443 push eax
0x00444444 mov eax, dword ptr ss:[ebp+0x8]
0x00444447 mov eax, dword ptr ds:[eax-0x4]
0x0044444A mov eax, dword ptr ds:[eax+0x24]
0x0044444D push eax
0x0044444E call 0x00406C7C
0x00406C7C jmp dword ptr ds:[0x009AB794]
0x77248200 jmp dword ptr ds:[0x772E1020]
0x767367E0 mov edi, edi
0x767367E2 push ebp
0x767367E3 mov ebp, esp
0x767367E5 push 0xFFFFFFFE
0x767367E7 push 0x76799550
0x767367EC push 0x767465E0
0x767367F1 mov eax, dword ptr fs:[0x00000000]
0x767367F7 push eax
0x767367F8 sub esp, 0x18
0x767367FB push ebx
0x767367FC push esi
0x767367FD push edi
0x767367FE mov eax, dword ptr ds:[0x767A2538]
0x76736803 xor dword ptr ss:[ebp-0x8], eax
0x76736806 xor eax, ebp
0x76736808 push eax
0x76736809 lea eax, ss:[ebp-0x10]
0x7673680C mov dword ptr fs:[0x00000000], eax

**Comment by sityware** [comment]
> Could you show the lines from the trace where it jumps into a system dll? If your claim is correct that the expression is already not working correctly then its possible that theres another bug hidden.

I'm still getting traces into system dlls.

When using:
Animate Into
Trace Into - When using 0x{p:cip} {i:cip} and condition mod.party(dis.branchdest(cip)) == 1

Where the jump happens, how it displays in x64dbg
00406C7C | FF25 94B79A00            | jmp dword ptr ds:[<&NtdllDefWindowProc_ |


0x00444434 mov eax, dword ptr ds:[eax-0x8]
0x00444437 mov eax, dword ptr ds:[eax+0x4]
0x0044443A push eax
0x0044443B mov eax, dword ptr ss:[ebp+0x8]
0x0044443E mov eax, dword ptr ds:[eax-0x8]
0x00444441 mov eax, dword ptr ds:[eax]
0x00444443 push eax
0x00444444 mov eax, dword ptr ss:[ebp+0x8]
0x00444447 mov eax, dword ptr ds:[eax-0x4]
0x0044444A mov eax, dword ptr ds:[eax+0x24]
0x0044444D push eax
0x0044444E call 0x00406C7C
0x00406C7C jmp dword ptr ds:[0x009AB794]
0x77248200 jmp dword ptr ds:[0x772E1020]
0x767367E0 mov edi, edi
0x767367E2 push ebp
0x767367E3 mov ebp, esp
0x767367E5 push 0xFFFFFFFE
0x767367E7 push 0x76799550
0x767367EC push 0x767465E0
0x767367F1 mov eax, dword ptr fs:[0x00000000]
0x767367F7 push eax
0x767367F8 sub esp, 0x18
0x767367FB push ebx
0x767367FC push esi
0x767367FD push edi
0x767367FE mov eax, dword ptr ds:[0x767A2538]
0x76736803 xor dword ptr ss:[ebp-0x8], eax
0x76736806 xor eax, ebp
0x76736808 push eax
0x76736809 lea eax, ss:[ebp-0x10]
0x7673680C mov dword ptr fs:[0x00000000], eax

**Comment by ZehMatt** [comment]
Thanks for the info, I'll have a look when I got some spare time.

**Comment by ZehMatt** [comment]
> > Could you show the lines from the trace where it jumps into a system dll? If your claim is correct that the expression is already not working correctly then its possible that theres another bug hidden.
> 
> I'm still getting traces into system dlls.
> 
> When using:
> Animate Into
> Trace Into - When using 0x{p:cip} {i:cip} and condition mod.party(dis.branchdest(cip)) == 1
> 
> Where the jump happens, how it displays in x64dbg
> 00406C7C | FF25 94B79A00 | jmp dword ptr ds:[<&NtdllDefWindowProc_ |
> 
> 0x00444434 mov eax, dword ptr ds:[eax-0x8]
> 0x00444437 mov eax, dword ptr ds:[eax+0x4]
> 0x0044443A push eax
> 0x0044443B mov eax, dword ptr ss:[ebp+0x8]
> 0x0044443E mov eax, dword ptr ds:[eax-0x8]
> 0x00444441 mov eax, dword ptr ds:[eax]
> 0x00444443 push eax
> 0x00444444 mov eax, dword ptr ss:[ebp+0x8]
> 0x00444447 mov eax, dword ptr ds:[eax-0x4]
> 0x0044444A mov eax, dword ptr ds:[eax+0x24]
> 0x0044444D push eax
> 0x0044444E call 0x00406C7C
> 0x00406C7C jmp dword ptr ds:[0x009AB794]
> 0x77248200 jmp dword ptr ds:[0x772E1020]
> 0x767367E0 mov edi, edi
> 0x767367E2 push ebp
> 0x767367E3 mov ebp, esp
> 0x767367E5 push 0xFFFFFFFE
> 0x767367E7 push 0x76799550
> 0x767367EC push 0x767465E0
> 0x767367F1 mov eax, dword ptr fs:[0x00000000]
> 0x767367F7 push eax
> 0x767367F8 sub esp, 0x18
> 0x767367FB push ebx
> 0x767367FC push esi
> 0x767367FD push edi
> 0x767367FE mov eax, dword ptr ds:[0x767A2538]
> 0x76736803 xor dword ptr ss:[ebp-0x8], eax
> 0x76736806 xor eax, ebp
> 0x76736808 push eax
> 0x76736809 lea eax, ss:[ebp-0x10]
> 0x7673680C mov dword ptr fs:[0x00000000], eax

I finally had a closer look and this is a situation where you can not trace over system calls, the last jmp is a tail-call so there is no way to jump around it, it would need to be able to detect tail-calls in order to place a breakpoint on the return address which is probably impossible to do correctly.

**Comment by brandonros** [comment]
@ZehMatt anything that could be done to get this wrapped up?

**Comment by ZehMatt** [comment]
> @ZehMatt anything that could be done to get this wrapped up?

See my last comment to why its rather hard to do.

**Comment by mrexodia** [comment]
Closing this because `StepUser` and `StepSystem` were implemented, which change the implementation.

**Pull request closed without merging**
