### PR TITLE
Use keys to select in dump

### PR DESCRIPTION
**Pull request by torusrxxx**
Arrow keys are now used to select in dump, not scroll in dump. Dump will scroll when selection is out of viewport. Shift key is to be supported.

### CODE REVIEW

**Comment by mrexodia** [comment]
Looks nice! I think it would be nice to keep some kind of original behavior with Ctrl+arrows though 

Maybe
Ctrl + up: scroll up one line without changing selection
Ctrl + down: scroll down one line without changing selection
Ctrl + left: first visible address - 1 without changing selection
Ctrl + right: first visible address + 1 without changing selection

What do you think?

**Comment by torusrxxx** [comment]
There is a problem with "first visible address ± 1" in floating number view. In development version of x64dbg, when you press ⇔ keys, the floating point numbers change into something meaningless, instead of displaying a next number. Therefore, I decide to shift a "word size" instead.

**Comment by justanotheranonymoususer** [comment]
> when you press ⇔ keys, the floating point numbers change into something meaningless

Or into something meaningful, if the number wasn't aligned to begin with

**Comment by mrexodia** [comment]
@justanotheranonymoususer my idea would be to allow using ctrl + left / right to move the view a single byte left/right. would this address your issue?

**Comment by justanotheranonymoususer** [comment]
Yep. Since it's the less common scenario, maybe make ctrl+arrow move a word, and ctrl+alt+arrow move a byte.

**Comment by mrexodia** [comment]
I tested and it appears to work very nicely @torusrxxx . Feel free to merge :)

**Pull request merged**
