### PR TITLE
GUI: do not draw EB00 (jmp to next instruction)

### PR DESCRIPTION
**Pull request by torusrxxx**
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/734)

### CODE REVIEW

**Comment by mrexodia** [comment]
why? it appears to be working fine here:

a

**Comment by torusrxxx** [comment]
I want this style:
x64dbg-no-jmp-eb00

**Comment by torusrxxx** [comment]
EB00 is not really a jump. It is merely a junk instruction.

**Comment by mrexodia** [comment]
I know and I think the behaviour is fine right now. If you really want to
disable it, maybe create an option somewhere...

**Pull request closed without merging**
