### PR TITLE
Trace recording

### PR DESCRIPTION
**Pull request by torusrxxx**

### CODE REVIEW

**Comment by torusrxxx** [comment]
Wishlist for the first version is cleared.

**Comment by mrexodia** [comment]
I fixed the conflicts and it should compile again now...

**Comment by gmastergreatee** [comment]
Incorrect Trace File Name
x64dbg bug

**Comment by torusrxxx** [comment]
Thanks for reporting, should be fixed now.

**Comment by gmastergreatee** [comment]
One more problem, I right-clicked on "Trace"  tab & selected "Delete". Now I'm unable to open the view again because there is no entry for __"Trace"__ window in "View" menu.

**Pull request merged**
