### PR TITLE
Oops! Fix a compilation error introduced recently

### PR DESCRIPTION
**Pull request by torusrxxx**
mWindowMainTitle is set to `tr("x64dbg")` however it is not of type QString. #643

---
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/645)

### CODE REVIEW

**Comment by torusrxxx** [comment]
Some one have to test the translation branch recently merged. I find it not work after reinstalling snapshots from GitHub. I forgot to upload some files I've changed.

**Comment by mrexodia** [comment]
i didnt test translation yet but i dont have a machine with chinese locale right now also probably the build scripts need to be updated to include the translation data right?

**Comment by torusrxxx** [comment]
No, you don't need a system with Chinese locale. You can rename the x64dbg_zh_CN.qm into x64dbg_(locale).qm . It will trick x64dbg into thinking you've installed the translation for your current locale. I'm wondering if it's even nessesary to provide language in preferences.

**Comment by mrexodia** [comment]
Alright, added some hidden settings to test translations. I'm Dutch myself but I would never use a Dutch version of x64dbg so it's nice to be able to change the default behavior of taking the system locale.

**Pull request merged**
