### PR TITLE
Set default hotkey for "Set Conditional Breakpoint"

### PR DESCRIPTION
**Pull request by justanotheranonymoususer**
Like OllyDbg has, very convenient

### CODE REVIEW

**Comment by mrexodia** [comment]
Thanks, no idea why the CI was not passing there...

**Comment by mrexodia** [comment]
Ah the reason was that you targeted `master` for some reason, but that's a dead branch

**Comment by mrexodia** [comment]
I recreated the commit and added it to development, thanks!

**Comment by justanotheranonymoususer** [comment]
It didn't work for some reason :(

**Comment by mrexodia** [comment]
For me it's working fine, I just had to edit `Actions -> Edit breakpoint` to be `Shift+F2` in `Options -> Shortcuts`

**Comment by justanotheranonymoususer** [comment]
Well, I hoped to set it as a default shortcut

**Comment by justanotheranonymoususer** [comment]
Still not :(

**Comment by mrexodia** [comment]
Try deleting your settings.

**Comment by justanotheranonymoususer** [comment]
I did. In fact I just downloaded a new version to a separate folder. In any case, lets hope the new pr fixes it.

**Pull request merged**
