### PR TITLE
Copy the stack

### PR DESCRIPTION
**Pull request by torusrxxx**
#232

---
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/707)

### CODE REVIEW

**Comment by mrexodia** [comment]
Hm I just pushed fixes for the register height

**Comment by torusrxxx** [comment]
I have re-applied it in the PR.

**Comment by torusrxxx** [comment]
This PR is for "copy text representation of stack" feature, not register height fix.

**Comment by torusrxxx** [comment]
repull it now

**Pull request closed without merging**
