### PR TITLE
St Patricks Day, March 17th, clover (32 & 64bit) icon

### PR DESCRIPTION
**Pull request by mrfearless**
obviously revert changes afterwards - if building with these icons, \src\exe\icon.rc, \src\exe\icon32.rc & \src\exe\icon64.rc need to be edited to point back to original bug.ico, bug32.ico and bug64.ico

Maybe a build script with different icons for different occasions could be implemented.

Happy St. Patrick's Day to all x64dbg users, contributors and developers.

---
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/1499)

### CODE REVIEW

**Comment by mrexodia** [comment]
🍀

**Comment by Mattiwatti** [comment]
Happy St Patrick's day!

When the bug comes back, can someone turn on PNG compression for the 64x64 and 128x128 icons? I once had a coworker who would have literally murdered me for wasting so much disk space.

ico

**Comment by mrexodia** [comment]
Haha I don't think it's really that much disk space but sure...

**Comment by Mattiwatti** [comment]
Of course, but you have to admit it looks funny ;) Over 50% saved! What will science think of next?

**Pull request merged**
