### PR TITLE
Browse dialog and goto dialog support auto-complete

### PR DESCRIPTION
**Pull request by torusrxxx**
x64dbg-goto-auto-complete

### CODE REVIEW

**Comment by torusrxxx** [comment]
Due to performance issues, there is a maximum count of 20 auto-complete entries.

**Comment by torusrxxx** [comment]
Very slow when loaded x64gui.pdb (36MB) and typed a symbol in it. The user has to type a space first to stop auto-complete.

**Comment by justanotheranonymoususer** [comment]
Have you considered using some optimized data structure, such as a balanced search tree? (i.e. `std::map`)
Also, why not use the component from the "Symbols" tab? It has a nice red underline, supports regex and all the goodness.

**Comment by torusrxxx** [comment]
There is no such data structure exist in x64dbg core. Also, we cannot store
gigabytes of symbol information in memory.

**Comment by justanotheranonymoususer** [comment]
OK, then maybe have a leveldb database on disk? It should be sorted and optimized for such queries.

**Comment by mrexodia** [comment]
You know you can use the symbols view right?

**Comment by justanotheranonymoususer** [comment]
Yes, but it's not as quick as Ctrl+G, and I need to to select all of the modules and stuff. Olly's (2) goto dialog is nice...

**Comment by mrexodia** [comment]
@torusrxxx perhaps we can cache only exported functions and just include those in the dialog like olly?

**Comment by justanotheranonymoususer** [comment]
Olly includes everything, not only exported functions

**Comment by torusrxxx** [comment]
There is one thing that this code can improve. Qt calls multiple times data() and then DbgSymAutoComplete() and then SymEnumSymbols(). I tried to cache the results for the same text but recieved segment faults, so the code is what it is.

**Comment by mrexodia** [comment]
I think this feature can be merged in after the conflicts are resolved and a setting has been added to disable it...

**Comment by mrexodia** [comment]
Very nice!

**Comment by mrexodia** [comment]
Hm, I just checked and it bugs out pretty hard if you use the down arrow to navigate the suggestions:

**Comment by torusrxxx** [comment]
Press arrow keys → textbox changes(selects a suggestion or a history record?) → candidates changes → qcompleter messed up

**Pull request merged**
